# Generated by Django 3.0.4 on 2020-04-19 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='path',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
