# Generated by Django 3.0.4 on 2020-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nav_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('question', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('question_short', models.CharField(max_length=100, null=True)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
    ]
