# Generated by Django 3.0.4 on 2020-05-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200426_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nav',
            old_name='fa_icon',
            new_name='icon',
        ),
    ]
